name: alitapricelist
description: "Alita Price List"

publish_to: 'none'

version: 1.6.4+25
environment:
  sdk: ^3.6.1

dependencies:
  collection: ^1.19.1
  cross_file: ^0.3.4+2
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  dropdown_search: ^5.0.6
  equatable: ^2.0.7
  file_picker: ^8.3.7
  file_saver: ^0.2.14
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^18.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  fluttertoast: ^8.2.11
  get_it: ^8.0.3
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  logger: ^2.5.0
  mockito: ^5.4.6
  path_provider: ^2.1.5
  pdf: ^3.11.3
  permission_handler: ^11.4.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  printing: ^5.14.2
  screenshot: ^3.0.0
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2
  timezone: ^0.9.2
  url_launcher: ^6.3.1
  googleapis_auth: ^1.4.1
  image: ^4.1.7
  flutter_dotenv: ^5.1.0
  http: ^1.5.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/logo/
    - .env
  fonts:
    - family: Inter
      fonts:
        - asset: assets/font/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/font/Inter-Italic-VariableFont_opsz,wght.ttf
          style: italic
